/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.text.DecimalFormat;
import java.text.NumberFormat;

/**
 *
 * @author amir.alsaify
 */
public class MainFrame extends javax.swing.JFrame {

	/**
	 * Creates new form CalcJFrame
	 */
	public MainFrame() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jOptionPane1 = new javax.swing.JOptionPane();
		jColorChooser1 = new javax.swing.JColorChooser();
		jColorChooser2 = new javax.swing.JColorChooser();
		jPanel1 = new javax.swing.JPanel();
		jToggleButton3 = new javax.swing.JToggleButton();
		butside1 = new javax.swing.JTextField();
		but1 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();
		butadd = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		butsin = new javax.swing.JToggleButton();
		jButton6 = new javax.swing.JButton();
		butqu = new javax.swing.JButton();
		jButton7 = new javax.swing.JButton();
		butrot = new javax.swing.JButton();
		jButton9 = new javax.swing.JButton();
		butfile2 = new javax.swing.JTextField();
		jToggleButton1 = new javax.swing.JToggleButton();
		jToggleButton2 = new javax.swing.JToggleButton();
		butresult = new javax.swing.JButton();

		jColorChooser2.setForeground(new java.awt.Color(0, 102, 102));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 100, Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 100, Short.MAX_VALUE));

		jToggleButton3.setText("jToggleButton3");

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("😀😀😂😂");

		butside1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				butside1ActionPerformed(evt);
			}
		});

		but1.setForeground(new java.awt.Color(204, 0, 51));
		but1.setText("Exit");
		but1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				but1ActionPerformed(evt);
			}
		});

		jButton4.setForeground(new java.awt.Color(0, 102, 102));
		jButton4.setText("x");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		jButton5.setForeground(new java.awt.Color(0, 204, 204));
		jButton5.setText("-");
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});

		butadd.setForeground(new java.awt.Color(0, 204, 204));
		butadd.setText("+");
		butadd.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				butaddActionPerformed(evt);
				
			}
		});

		jButton2.setForeground(new java.awt.Color(0, 102, 102));
		jButton2.setText("/");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		butsin.setText("sin(x)");
		butsin.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				butsinActionPerformed(evt);
			}
		});

		jButton6.setText("cos(x");
		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton6ActionPerformed(evt);
			}
		});

		butqu.setText("x^2");
		butqu.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				butquActionPerformed(evt);
			}
		});

		jButton7.setText("x^3");
		jButton7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton7ActionPerformed(evt);
			}
		});

		butrot.setText("√");
		butrot.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				butrotActionPerformed(evt);
			}
		});

		jButton9.setText("e");
		jButton9.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton9ActionPerformed(evt);
			}
		});

		butfile2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				butfile2ActionPerformed(evt);
			}
		});

		jToggleButton1.setText("FirstNumber1");

		jToggleButton2.setText("SecondNumber2");

		butresult.setText("result");
		butresult.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				butresultActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup().addContainerGap()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 128,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 117,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(butside1).addComponent(butfile2)))
				.addGroup(layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(butadd).addComponent(butqu))
						.addGap(27, 27, 27)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(butsin, javax.swing.GroupLayout.PREFERRED_SIZE, 75,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jButton5))
						.addGap(30, 30, 30)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addGroup(layout.createSequentialGroup().addComponent(jButton4).addGap(18, 18, 18)
										.addComponent(jButton2))
								.addGroup(layout.createSequentialGroup().addComponent(jButton6)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 78,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
								.addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 76,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(butrot).addGap(120, 120, 120))
				.addGroup(layout.createSequentialGroup().addGroup(layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(132, 132, 132).addComponent(but1))
						.addGroup(layout.createSequentialGroup().addGap(38, 38, 38).addComponent(butresult,
								javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGap(0, 0, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(butside1, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jToggleButton1))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(butfile2, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jToggleButton2))
				.addGap(15, 15, 15).addComponent(butresult)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(butadd)
						.addComponent(jButton5).addComponent(jButton4).addComponent(jButton2))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(butqu)
						.addComponent(butsin).addComponent(jButton6).addComponent(jButton9))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(butrot)
						.addComponent(jButton7))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(but1)
				.addContainerGap(18, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	private void butside1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
		double num1 = Double.parseDouble(butside1.getText());
		double num2 = Double.parseDouble(butfile2.getText());
		double result = num1 - num2;
		butresult.setText(String.valueOf(result));
	}

	private void but1ActionPerformed(java.awt.event.ActionEvent evt) {
		System.exit(0);
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		double num1 = Double.parseDouble(butside1.getText());
		double num2 = Double.parseDouble(butfile2.getText());
		double result = num1 / num2;
		butresult.setText(String.valueOf(result));
	}

	private void butaddActionPerformed(java.awt.event.ActionEvent evt) {
		double num1 = Double.parseDouble(butside1.getText());
		double num2 = Double.parseDouble(butfile2.getText());
		double result = num1 + num2;
		butresult.setText(String.valueOf(result));

	}

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		double num1 = Double.parseDouble(butside1.getText());
		double num2 = Double.parseDouble(butfile2.getText());
		double result = num1 * num2;
		butresult.setText(String.valueOf(result));
	}

	private void butsinActionPerformed(java.awt.event.ActionEvent evt) {
		double num1 = Double.parseDouble(butside1.getText());
		double valueRadians = Math.toRadians(num1);
		double radians = Math.sin(valueRadians);
		butresult.setText(String.valueOf(valueRadians));
	}

	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {

		double num1 = Double.parseDouble(butside1.getText());
		double valueRadians = Math.toRadians(num1);
		double radians = Math.cos(valueRadians);
		butresult.setText(String.valueOf(valueRadians));
	}

	private void butquActionPerformed(java.awt.event.ActionEvent evt) {
		double num1 = Double.parseDouble(butside1.getText());
		double result = Math.pow(num1, 2);
		butresult.setText(String.valueOf(result));
	}

	private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
		double num1 = Double.parseDouble(butside1.getText());
		double result = Math.pow(num1, 3);
		butresult.setText(String.valueOf(result));
	}

	private void butrotActionPerformed(java.awt.event.ActionEvent evt) {
		double num1 = Double.parseDouble(butside1.getText());
		double result = Math.sqrt(num1);
		butresult.setText(String.valueOf(result));

	}

	private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {
		double num1 = Double.parseDouble(butside1.getText());
		double result = 2.71828182846;
		butresult.setText(String.valueOf(result));
	}

	private void butfile2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void butresultActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		new MainFrame().setVisible(true);

	}

	// Variables declaration - do not modify
	private javax.swing.JButton but1;
	private javax.swing.JButton butadd;
	private javax.swing.JTextField butfile2;
	private javax.swing.JButton butqu;
	private javax.swing.JButton butresult;
	private javax.swing.JButton butrot;
	private javax.swing.JTextField butside1;
	private javax.swing.JToggleButton butsin;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JButton jButton9;
	private javax.swing.JColorChooser jColorChooser1;
	private javax.swing.JColorChooser jColorChooser2;
	private javax.swing.JOptionPane jOptionPane1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JToggleButton jToggleButton1;
	private javax.swing.JToggleButton jToggleButton2;
	private javax.swing.JToggleButton jToggleButton3;
	// End of variables declaration
}
